#version: "3.8"

services:
  jupyter:
    image: lalvarezl/all-spark-notebook:latest
    container_name: all-spark-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=1234
    volumes:
      - ../../mis-archivos/mis-proyectos:/home/jovyan/work
      #- ./notebooks:/app
    networks:
      - ml_net

  postgres:
    image: lalvarezl/postgresql:laal
    container_name: postgresql
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow123
      POSTGRES_DB: mlflow_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ml_net

  mlflow:
    image: lalvarezl/mlflow:laal
    container_name: mlflow
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow123@postgres:5432/mlflow_db
    volumes:
      #- ./mlruns:/app/mlruns
      - ../../mis-archivos/mlruns:/home/jovyan/work
    command: >
      mlflow ui
      --backend-store-uri postgresql://mlflow:mlflow123@postgres:5432/mlflow_db
      --host 0.0.0.0
      --port 5000
    networks:
      - ml_net

volumes:
  postgres_volume:
    name: postgres_volume

networks:
  ml_net:
  